// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/AntonioTWize/goledger/handlers"
	"github.com/AntonioTWize/goledger/routes"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeServer() (*echo.Echo, error) {
	chargeHandler := handlers.NewChargeHandler()
	echoEcho := routes.NewRouter(chargeHandler)
	return echoEcho, nil
}
